feat: utils: add function __assert_function
radxa-pkg/librtui pull request #10
Opened 2024-07-18 10:32 UTC by CodeChenL

2024-07-18 10:45 UTC, RadxaYuntian requested changes

2024-07-18 10:45 UTC, RadxaYuntian commented on src/lib/librtui/utils/utils.sh
> +__assert_function() {
```suggestion
__external_script_type_check() {
```

2024-07-18 10:45 UTC, RadxaYuntian commented on src/lib/librtui/utils/utils.sh
> +		return $?
这里返回的是0

2024-07-18 10:45 UTC, RadxaYuntian commented on src/lib/librtui/utils/utils.sh
> +	elif ! bash -c "source /usr/lib/librtui/utils/utils.sh && source $1 && __parameter_type_check $2 function"; then
可能librtui也需要一个类似rsetup的用来专门执行函数的入口，这样才可以保证函数运行的环境设置是一样的（set -euo pipefail这类）。
设置了set -e后就直接执行这两个命令就好，失败了就自动退出函数并返回对应的错误值

2024-07-19 03:08 UTC, RadxaYuntian requested changes
另外在usr/libexec/librtui里面加一个入口脚本

2024-07-19 03:08 UTC, RadxaYuntian commented on src/lib/librtui/utils/utils.sh
> +	bash -c "source /usr/lib/librtui/utils/utils.sh && source "$1" && __parameter_type_check "$2" function"
```suggestion
	bash -c "source /usr/lib/librtui/utils/utils.sh && source '$1' && __parameter_type_check '$2' function"
```
你在双引号里面再用双引号就会结束字符串了啊，这样如果你变量里面有空格就会被分割成多个参数

2024-07-19 03:08 UTC, RadxaYuntian commented on src/lib/librtui/utils/utils.sh
> +	__assert_f "$1"
```suggestion
	__assert_f "$1"

```
这还是参数检查的一部分

2024-07-19 03:12 UTC, RadxaYuntian commented
入口脚本可能不用，如果rsetup那边执行没有问题的话

2024-07-19 03:19 UTC, RadxaYuntian commented on src/lib/librtui/utils/utils.sh
> +	__parameter_count_check 2 "$@"
```suggestion
	__parameter_count_check 3 "$@"
```

2024-07-19 03:21 UTC, RadxaYuntian commented
我感觉我们的bash脚本也应该加上单元测试代码，可以弄一个测试各个场景的返回值

2024-07-19 03:22 UTC, RadxaYuntian commented
https://github.com/kward/shunit2

2024-07-19 03:24 UTC, RadxaYuntian commented
https://github.com/dodie/testing-in-bash?tab=readme-ov-file

感觉shellspec更好一点

2024-07-19 03:46 UTC, CodeChenL commented
> https://github.com/dodie/testing-in-bash?tab=readme-ov-file
> 
> 感觉shellspec更好一点

现在搞吗

2024-07-19 03:47 UTC, RadxaYuntian commented
unit test我之后看看吧

2024-07-19 03:48 UTC, RadxaYuntian requested changes
squash

2024-07-19 05:59 UTC, RadxaYuntian approved these changes

2024-07-19 06:00 UTC, merged