feat: add util function get_real_user
radxa-pkg/librtui pull request #7
Opened 2024-06-24 03:20 UTC by CodeChenL

配合 https://github.com/radxa-pkg/rsetup/pull/62/files#r1650271993

2024-06-24 03:49 UTC, RadxaYuntian requested changes

2024-06-24 03:49 UTC, RadxaYuntian commented on src/lib/librtui/utils/utils.sh
> +	if [ -n "$PKEXEC_UID" ]; then
```suggestion
	if [[ -n "$PKEXEC_UID" ]]; then
```

2024-06-24 03:49 UTC, RadxaYuntian commented on src/lib/librtui/utils/utils.sh
> +	elif [ -n "$SUDO_USER" ]; then
```suggestion
	elif [[ -n "$SUDO_USER" ]]; then
```

2024-06-24 03:49 UTC, RadxaYuntian commented on src/lib/librtui/utils/utils.sh
> +		user="$(id -nu)"
在那边有说$USER和whoami的返回在使用su的时候是不同的，麻烦验证一下是不是这样，以及id会不会和whoami有一样的问题

2024-06-24 10:27 UTC, CodeChenL commented on src/lib/librtui/utils/utils.sh
> +		user="$(id -nu)"
```bash
rock@rock-5b:~$ sudo bash
root@rock-5b:/home/rock# get_real_user() {
        # return name of the user that runs the script
        local user=''

        if [ -n "$PKEXEC_UID" ]; then
                user="$(id -nu "$PKEXEC_UID")"
        elif [ -n "$SUDO_USER" ]; then
                user="$SUDO_USER"
        else
                user="$(id -nu)"
        fi

        echo "$user"
}
root@rock-5b:/home/rock# get_real_user 
rock
root@rock-5b:/home/rock# echo "$(id -nu)"
root
root@rock-5b:/home/rock# echo "$SUDO_USER"
rock
root@rock-5b:/home/rock# echo "$(id -nu "$PKEXEC_UID")"
id: ‘’: no such user: No such file or directory

root@rock-5b:/home/rock# whoami
root
root@rock-5b:/home/rock# 
```

2024-06-24 10:29 UTC, RadxaYuntian commented on src/lib/librtui/utils/utils.sh
> +		user="$(id -nu)"
说的是su不是sudo啊

2024-06-24 10:32 UTC, CodeChenL commented on src/lib/librtui/utils/utils.sh
> +		user="$(id -nu)"
> 说的是su不是sudo啊
```bash
rock@rock-5b:~$ su
Password: 
root@rock-5b:/home/rock# get_real_user() {
        # return name of the user that runs the script
        local user=''

        if [ -n "$PKEXEC_UID" ]; then
                user="$(id -nu "$PKEXEC_UID")"
        elif [ -n "$SUDO_USER" ]; then
                user="$SUDO_USER"
        else
                user="$(id -nu)"
        fi

        echo "$user"
}
root@rock-5b:/home/rock# get_real_user 
root
root@rock-5b:/home/rock# echo "$(id -nu)"
root
root@rock-5b:/home/rock# echo "$SUDO_USER"

root@rock-5b:/home/rock# echo "$(id -nu "$PKEXEC_UID")"
id: ‘’: no such user: No such file or directory

root@rock-5b:/home/rock# whoami
root
root@rock-5b:/home/rock# 
```

2024-06-24 10:41 UTC, CodeChenL commented on src/lib/librtui/utils/utils.sh
> +		user="$(id -nu)"
已修改为使用$USER

2024-06-24 10:43 UTC, RadxaYuntian requested changes

2024-06-24 10:43 UTC, RadxaYuntian commented on src/lib/librtui/utils/utils.sh
> +		echo "$(id -nu "$PKEXEC_UID")"
```suggestion
		id -nu "$PKEXEC_UID"
```
shellcheck没有检查出来么？

2024-06-25 06:07 UTC, CodeChenL commented on src/lib/librtui/utils/utils.sh
> +		echo "$(id -nu "$PKEXEC_UID")"
这个仓库我本地没开pre-commit，没注意到有pre从-commit

2024-06-25 06:18 UTC, RadxaYuntian approved these changes

2024-06-25 06:18 UTC, merged